import '../models/exercise.dart';

class ExerciseService {
  static final Map<String, List<Exercise>> _weeklyPlan = {
    'Segunda-feira': [
        Exercise(
            id: 'supino_com_halteres',
            name: 'Supino com Halteres',
            category: '',
            targetedMuscles: [''],  
            description: 'Descrição Supino com Halteres',  
            equipmentNeeded: ['Equipamento Supino com Halteres'],  
            days: ['Domingo'],  
        ),
        
        Exercise(
            id: 'elevações_frontais_com_cabo',
            name: 'Elevações Frontais com Cabo',
            category: '',  
            targetedMuscles: [''],  
            description: 'Descrição Elevações Frontais com Cabo',  
            equipmentNeeded: ['Equipamento Elevações Frontais com Cabo'],  
            days: ['Domingo'],  
        ),
        
        Exercise(
            id: 'elevações_laterais_com_halteres',
            name: 'Elevações Laterais com Halteres',
            category: '',  
            targetedMuscles: [''],  
            description: 'Descrição Elevações Laterais com Halteres',  
            equipmentNeeded: ['Equipamento Elevações Laterais com Halteres'],  
            days: ['Domingo'],  
        ),
        
        Exercise(
            id: 'pressão_de_peito_com_cabo',
            name: 'Pressão de Peito com Cabo',
            category: '',  
            targetedMuscles: [''],  
            description: 'Descrição Pressão de Peito com Cabo',  
            equipmentNeeded: ['Equipamento Pressão de Peito com Cabo'],  
            days: ['Domingo'],  
        ),
        
      Exercise(
        id: 'incline_dumbbell_bench_press',
        name: 'Incline Supino com Halteres',
        category: 'Cabeça clavicular do grande peitoral',
        targetedMuscles: ['Cabeça clavicular do grande peitoral', 'Tríceps', 'Deltoides anteriores'],
        description: 'Descrição Incline Supino com Halteres',
        equipmentNeeded: ['Equipamento necessário para Incline Supino com Halteres'],
        days: ['Domingo'],
      ),

      Exercise(
        id: 'cable_front_raises',
        name: 'Elevações Frontais com Cabo',
        category: 'Cabeça clavicular do grande peitoral',
        targetedMuscles: ['Cabeça clavicular do grande peitoral', 'Deltoides anteriores'],
        description: 'Descrição para Elevações Frontais com Cabo',
        equipmentNeeded: ['Equipamento necessário para Elevações Frontais com Cabo'],
        days: ['Domingo'],
      ),

      Exercise(
        id: 'peck_deck_flies',
        name: 'Peck Deck',
        category: 'Cabeça esternocostal do grande peitoral',
        targetedMuscles: ['Cabeça esternocostal do grande peitoral', 'Tríceps', 'Deltoides anteriores'],
        description: 'Descrição para Peck Deck',
        equipmentNeeded: ['Equipamento necessário para Peck Deck'],
        days: ['Domingo'],
      ),

      Exercise(
        id: 'dumbbell_bench_press',
        name: 'Supino com Halteres',
        category: 'Cabeça esternocostal do grande peitoral',
        targetedMuscles: ['Cabeça esternocostal do grande peitoral', 'Tríceps', 'Deltoides anteriores'],
        description: 'Descrição para Supino com Halteres',
        equipmentNeeded: ['Equipamento necessário para Supino com Halteres'],
        days: ['Domingo'],
      ),
Exercise(
                id: 'incline_dumbbell_bench_press',
                name: 'Incline Supino com Halteres',
                category: 'Exercício de segunda-feira',
                targetedMuscles: ['Cabeça clavicular do grande peitoral', 'Tríceps', 'Deltoides anteriores'],
                description: 'Descrição para Incline Supino com Halteres',
                equipmentNeeded: ['Equipamento necessário para Incline Supino com Halteres'],
                days: ['Segunda-feira'],
            ),
    Exercise(
                id: 'cable_front_raises',
                name: 'Elevações Frontais com Cabo',
                category: 'Exercício de segunda-feira',
                targetedMuscles: ['Cabeça clavicular do grande peitoral', 'Deltoides anteriores'],
                description: 'Descrição para Elevações Frontais com Cabo',
                equipmentNeeded: ['Equipamento necessário para Elevações Frontais com Cabo'],
                days: ['Segunda-feira'],
            ),
    Exercise(
                id: 'peck_deck_flies',
                name: 'Peck Deck',
                category: 'Exercício de segunda-feira',
                targetedMuscles: ['Cabeça esternocostal do grande peitoral', 'Tríceps', 'Deltoides anteriores'],
                description: 'Descrição para Peck Deck',
                equipmentNeeded: ['Equipamento necessário para Peck Deck'],
                days: ['Segunda-feira'],
            ),
    Exercise(
                id: 'dumbbell_bench_press',
                name: 'Supino com Halteres',
                category: 'Exercício de segunda-feira',
                targetedMuscles: ['Cabeça esternocostal do grande peitoral', 'Tríceps', 'Deltoides anteriores'],
                description: 'Descrição para Supino com Halteres',
                equipmentNeeded: ['Equipamento necessário para Supino com Halteres'],
                days: ['Segunda-feira'],
            ),
    
      Exercise(
        id: '1',
        name: 'Supino',
        category: 'Push',
        targetedMuscles: ['Peitorais', 'Tríceps'],
        description: 'Um exercício básico de empurrar para o corpo superior.',
        equipmentNeeded: ['Barra'],
        days: ['Domingo'],
      ),
    ],
    'Terça-feira': [
        Exercise(
            id: 'pulldown',
            name: 'Pulldown',
            category: '',  
            targetedMuscles: [''],  
            description: 'Descrição Pulldown',  
            equipmentNeeded: ['Equipamento Pulldown'],  
            days: ['Domingo'],  
        ),
        
        Exercise(
            id: 'remada_sentado',
            name: 'Remada Sentado',
            category: '',  
            targetedMuscles: [''],  
            description: 'Descrição Remada Sentado',  
            equipmentNeeded: ['Equipamento Remada Sentado'],  
            days: ['Domingo'],  
        ),
        
        Exercise(
            id: 'curl_com_halteres',
            name: 'Curl com Halteres',
            category: '',  
            targetedMuscles: [''],  
            description: 'Descrição Curl com Halteres',  
            equipmentNeeded: ['Equipamento Curl com Halteres'],  
            days: ['Domingo'],  
        ),
        Exercise(
                id: 'peck_deck_rear_delt_flies',
                name: 'Peck Deck Rear Delt Flies',
                category: 'Exercício de terça-feira',
                targetedMuscles: ['Deltoides posteriores', 'Romboides', 'Trapézio'],
                description: 'Descrição para Peck Deck Rear Delt Flies',
                equipmentNeeded: ['Equipamento necessário para Peck Deck Rear Delt Flies'],
                days: ['Terça-feira'],
            ),
    Exercise(
                id: 'seated_rows',
                name: 'Seated Rows',
                category: 'Exercício de terça-feira',
                targetedMuscles: ['Trapézio', 'Romboides', 'Latíssimo do dorso'],
                description: 'Descrição para Seated Rows',
                equipmentNeeded: ['Equipamento necessário para Seated Rows'],
                days: ['Terça-feira'],
            ),
    Exercise(
                id: 'lat_pulldown',
                name: 'Lat Pulldown',
                category: 'Exercício de terça-feira',
                targetedMuscles: ['Latíssimo do dorso', 'Bíceps braquial', 'Braquial', 'Braquiorradial'],
                description: 'Descrição para Lat Pulldown',
                equipmentNeeded: ['Equipamento necessário para Lat Pulldown'],
                days: ['Terça-feira'],
            ),
    Exercise(
                id: 't_bar_rows',
                name: 'T-bar Rows',
                category: 'Exercício de terça-feira',
                targetedMuscles: ['Latíssimo do dorso', 'Romboides', 'Trapézio médio'],
                description: 'Descrição para T-bar Rows',
                equipmentNeeded: ['Equipamento necessário para T-bar Rows'],
                days: ['Terça-feira'],
            ),
    Exercise(
                id: 'inclined_bicep_curls',
                name: 'Inclined Curl de Bíceps',
                category: 'Exercício de terça-feira',
                targetedMuscles: ['Cabeça longa do bíceps', 'Braquial'],
                description: 'Descrição para Inclined Curl de Bíceps',
                equipmentNeeded: ['Equipamento necessário para Inclined Curl de Bíceps'],
                days: ['Terça-feira'],
            ),
    Exercise(
                id: 'preacher_bicep_curls',
                name: 'Preacher Curl de Bíceps',
                category: 'Exercício de terça-feira',
                targetedMuscles: ['Cabeça curta do bíceps', 'Braquial'],
                description: 'Descrição para Preacher Curl de Bíceps',
                equipmentNeeded: ['Equipamento necessário para Preacher Curl de Bíceps'],
                days: ['Terça-feira'],
            ),
    Exercise(
                id: 'bicep_curls',
                name: 'Curl de Bíceps',
                category: 'Exercício de terça-feira',
                targetedMuscles: ['Bíceps', 'Braquial'],
                description: 'Descrição para Curl de Bíceps',
                equipmentNeeded: ['Equipamento necessário para Curl de Bíceps'],
                days: ['Terça-feira'],
            ),
    Exercise(
                id: 'cable_bicep_curls',
                name: 'Curl de Bíceps com Cabo',
                category: 'Exercício de terça-feira',
                targetedMuscles: ['Bíceps', 'Braquial'],
                description: 'Descrição para Curl de Bíceps com Cabo',
                equipmentNeeded: ['Equipamento necessário para Curl de Bíceps com Cabo'],
                days: ['Terça-feira'],
            ),
    
      Exercise(
        id: '2',
        name: 'Pull Ups',
        category: 'Pull',
        targetedMuscles: ['Costas', 'Bíceps'],
        description: 'Um exercício fundamental de puxar para o corpo superior.',
        equipmentNeeded: ['Barra de pull-up'],
        days: ['Terça-feira', 'Sábado'],
      ),
    ],
    'Quarta-feira': [Exercise(
                id: 'unilateral_cable_lateral_raises',
                name: 'Levantamentos Laterais com Cabo Unilateral',
                category: 'Exercício de quarta-feira',
                targetedMuscles: ['Deltoides médios'],
                description: 'Descrição para Levantamentos Laterais com Cabo Unilateral',
                equipmentNeeded: ['Equipamento necessário para Levantamentos Laterais com Cabo Unilateral'],
                days: ['Quarta-feira'],
            ),
    Exercise(
                id: 'dumbbell_lateral_raises',
                name: 'Levantamentos Laterais com Halteres',
                category: 'Exercício de quarta-feira',
                targetedMuscles: ['Deltoides médios'],
                description: 'Descrição para Levantamentos Laterais com Halteres',
                equipmentNeeded: ['Equipamento necessário para Levantamentos Laterais com Halteres'],
                days: ['Quarta-feira'],
            ),
    Exercise(
                id: 'unilateral_cable_tricep_overhead_extensions',
                name: 'Extensões de Tríceps Sobre a Cabeça com Cabo Unilateral',
                category: 'Exercício de quarta-feira',
                targetedMuscles: ['Tríceps braquial (cabeça longa)'],
                description: 'Descrição para Extensões de Tríceps Sobre a Cabeça com Cabo Unilateral',
                equipmentNeeded: ['Equipamento necessário para Extensões de Tríceps Sobre a Cabeça com Cabo Unilateral'],
                days: ['Quarta-feira'],
            ),
    Exercise(
                id: 'unilateral_cable_tricep_extensions',
                name: 'Extensões de Tríceps com Cabo Unilateral',
                category: 'Exercício de quarta-feira',
                targetedMuscles: ['Tríceps braquial'],
                description: 'Descrição para Extensões de Tríceps com Cabo Unilateral',
                equipmentNeeded: ['Equipamento necessário para Extensões de Tríceps com Cabo Unilateral'],
                days: ['Quarta-feira'],
            ),
    ],
    'Quinta-feira': [
        Exercise(
            id: 'supino_inclinado_com_halteres',
            name: 'Supino Inclinado com Halteres',
            category: '',  
            targetedMuscles: [''],  
            description: 'Descrição Supino Inclinado com Halteres',  
            equipmentNeeded: ['Equipamento Supino Inclinado com Halteres'],  
            days: ['Domingo'],  
        ),
        
        Exercise(
            id: 'pressão_de_ombro',
            name: 'Pressão de Ombro',
            category: '',  
            targetedMuscles: [''],  
            description: 'Descrição Pressão de Ombro',  
            equipmentNeeded: ['Equipamento Pressão de Ombro'],  
            days: ['Domingo'],  
        ),
        
        Exercise(
            id: 'peck_deck',
            name: 'Peck Deck',
            category: '',  
            targetedMuscles: [''],  
            description: 'Descrição Peck Deck',  
            equipmentNeeded: ['Equipamento Peck Deck'],  
            days: ['Domingo'],  
        ),
        
        Exercise(
            id: 'mergulho',
            name: 'Mergulho',
            category: '',  
            targetedMuscles: [''],  
            description: 'Descrição Mergulho',  
            equipmentNeeded: ['Equipamento Mergulho'],  
            days: ['Domingo'],  
        ),
        Exercise(
                id: 'leg_curls',
                name: 'Leg Curls',
                category: 'Exercício de quinta-feira',
                targetedMuscles: ['Isquiotibiais'],
                description: 'Descrição para Leg Curls',
                equipmentNeeded: ['Equipamento necessário para Leg Curls'],
                days: ['Quinta-feira'],
            ),
    Exercise(
                id: 'leg_extensions',
                name: 'Leg Extensions',
                category: 'Exercício de quinta-feira',
                targetedMuscles: ['Quadríceps'],
                description: 'Descrição para Leg Extensions',
                equipmentNeeded: ['Equipamento necessário para Leg Extensions'],
                days: ['Quinta-feira'],
            ),
    Exercise(
                id: 'leg_press',
                name: 'Leg Press',
                category: 'Exercício de quinta-feira',
                targetedMuscles: ['Quadríceps', 'Isquiotibiais', 'Músculos glúteos'],
                description: 'Descrição para Leg Press',
                equipmentNeeded: ['Equipamento necessário para Leg Press'],
                days: ['Quinta-feira'],
            ),
    Exercise(
                id: 'squats',
                name: 'Squats',
                category: 'Exercício de quinta-feira',
                targetedMuscles: ['Quadríceps', 'Isquiotibiais', 'Glúteo máximo', 'Adutores', 'Parte inferior das costas'],
                description: 'Descrição para Squats',
                equipmentNeeded: ['Equipamento necessário para Squats'],
                days: ['Quinta-feira'],
            ),
    
      Exercise(
        id: '3',
        name: 'Squats',
        category: 'Pernas',
        targetedMuscles: ['Quadríceps', 'Glúteos'],
        description: 'Um exercício composto fundamental para o dia das pernas',
        equipmentNeeded: ['Barra'],
        days: ['Quinta-feira'],
      ),
    ],
    'Sexta-feira': [
        Exercise(
            id: 'remada_com_t-bar_apoiada',
            name: 'Remada com T-bar Apoiada',
            category: '',  
            targetedMuscles: [''],  
            description: 'Descrição Remada com T-bar Apoiada',  
            equipmentNeeded: ['Equipamento Remada com T-bar Apoiada'],  
            days: ['Domingo'],  
        ),
        
        Exercise(
            id: 'pulldown_unilateral',
            name: 'Pulldown Unilateral',
            category: '',  
            targetedMuscles: [''],  
            description: 'Descrição Pulldown Unilateral',  
            equipmentNeeded: ['Equipamento Pulldown Unilateral'],  
            days: ['Domingo'],  
        ),
        
        Exercise(
            id: 'voo_do_deltóide_posterior',
            name: 'Voo do Deltóide Posterior',
            category: '',  
            targetedMuscles: [''],  
            description: 'Descrição Voo do Deltóide Posterior',  
            equipmentNeeded: ['Equipamento Voo do Deltóide Posterior'],  
            days: ['Domingo'],  
        ),
        
        Exercise(
            id: 'curl_de_bíceps_com_barra',
            name: 'Curl de Bíceps com Barra',
            category: '',  
            targetedMuscles: [''],  
            description: 'Descrição Curl de Bíceps com Barra',  
            equipmentNeeded: ['Equipamento Curl de Bíceps com Barra'],  
            days: ['Domingo'],  
        ),
        
    ],
    'Sábado': [
    ],
    'Domingo': [
      Exercise(
        id: '4',
        name: 'Corrida Leve',
        category: 'Cardio',
        targetedMuscles: ['Pernas'],
        description: 'Um exercício cardio leve para terminar a semana',
        equipmentNeeded: ['Nenhum'],
        days: ['Domingo'],
      ),
    ],
  };

  static List<Exercise> getExercisesForDay(String day) {
    return _weeklyPlan[day] ?? [];
  }
}
