// services/exercise_service.dart

import '../models/exercise.dart';
import 'package:flexform/models/selection_data.dart';

class ExerciseService {
  static final List<Exercise> _exercises = [
    Exercise(
      id: '1',
      name: 'Supino com Halteres',
      category: 'Peitoral',
      targetedMuscles: ['Cabeça esternocostal do peitoral maior', 'Tríceps', 'Deltoides anteriores'],
      description: 'Este exercício utiliza halteres para trabalhar principalmente a cabeça esternocostal do peitoral maior, tríceps e deltoides anteriores.',
      equipmentNeeded: ['Halteres'],
      days: ['segunda-feira', 'quinta-feira'],
    ),
    Exercise(
      id: '2',
      name: 'Voador no Peck Deck',
      category: 'Peitoral',
      targetedMuscles: ['Cabeça esternocostal do peitoral maior', 'Tríceps', 'Deltoides anteriores'],
      description: 'Este exercício isola a cabeça esternocostal do peitoral maior, realizado na máquina Peck Deck.',
      equipmentNeeded: ['Máquina Peck Deck'],
      days: ['segunda-feira', 'quinta-feira'],
    ),
    Exercise(
      id: '3',
      name: 'Elevações Frontais em Polia',
      category: 'Peitoral',
      targetedMuscles: ['Cabeça clavicular do peitoral maior', 'Deltoides anteriores'],
      description: 'Este exercício trabalha a cabeça clavicular do peitoral maior e os deltoides anteriores, realizado com polia.',
      equipmentNeeded: ['Polia'],
      days: ['segunda-feira', 'quinta-feira'],
    ),
    Exercise(
      id: '4',
      name: 'Supino Inclinado com Halteres',
      category: 'Peitoral',
      targetedMuscles: ['Cabeça clavicular do peitoral maior', 'Tríceps', 'Deltoides anteriores'],
      description: 'Realizado em um banco inclinado, este exercício foca na cabeça clavicular do peitoral maior, além de tríceps e deltoides anteriores.',
      equipmentNeeded: ['Halteres', 'Banco Inclinado'],
      days: ['segunda-feira', 'quinta-feira'],
    ),
    Exercise(
      id: '5',
      name: 'Rosca de Bíceps em Polia',
      category: 'Braços',
      targetedMuscles: ['Bíceps', 'Braquial'],
      description: 'Focado nos bíceps e no músculo braquial, este exercício é realizado com polia.',
      equipmentNeeded: ['Polia'],
      days: ['terça-feira', 'sexta-feira'],
    ),
    Exercise(
      id: '6',
      name: 'Rosca de Bíceps com Halteres',
      category: 'Braços',
      targetedMuscles: ['Bíceps', 'Braquial'],
      description: 'Exercício clássico para bíceps que pode ser realizado de pé ou sentado, utilizando halteres.',
      equipmentNeeded: ['Halteres'],
      days: ['terça-feira', 'sexta-feira'],
    ),
    Exercise(
      id: '7',
      name: 'Rosca Scott',
      category: 'Braços',
      targetedMuscles: ['Bíceps'],
      description: 'Conhecida também como rosca predicador, é um exercício que trabalha a cabeça curta do bíceps, realizada em um banco Scott com halteres ou barra.',
      equipmentNeeded: ['Banco Scott', 'Halteres ou Barra'],
      days: ['terça-feira', 'sexta-feira'],
    ),
    Exercise(
      id: '8',
      name: 'Rosca de Bíceps Inclinada',
      category: 'Braços',
      targetedMuscles: ['Bíceps'],
      description: 'Este exercício é realizado em um banco inclinado, enfatizando a cabeça longa do bíceps, utilizando halteres.',
      equipmentNeeded: ['Banco Inclinado', 'Halteres'],
      days: ['terça-feira', 'sexta-feira'],
    ),
    Exercise(
      id: '9',
      name: 'Tríceps na Polia Alta',
      category: 'Braços',
      targetedMuscles: ['Tríceps'],
      description: 'Exercício de tríceps realizado na polia alta, que pode ser feito com corda, barra ou pegada invertida.',
      equipmentNeeded: ['Polia Alta', 'Corda ou Barra'],
      days: ['segunda-feira', 'quinta-feira'],
    ),
    Exercise(
      id: '10',
      name: 'Tríceps Testa na Polia Alta',
      category: 'Braços',
      targetedMuscles: ['Tríceps'],
      description: 'Este exercício foca na parte superior dos tríceps, realizado com uma pegada em supinação na polia alta.',
      equipmentNeeded: ['Polia Alta'],
      days: ['segunda-feira', 'quinta-feira'],
    ),
    Exercise(
      id: '11',
      name: 'Remada T com Barra',
      category: 'Costas',
      targetedMuscles: ['Dorsais', 'Trapézio', 'Romboides'],
      description: 'Este exercício fortalece as costas, focando nos músculos dorsais, trapézio e romboides, utilizando uma barra em forma de T.',
      equipmentNeeded: ['Barra T'],
      days: ['terça-feira', 'sexta-feira'],
    ),
    Exercise(
      id: '12',
      name: 'Pulldown na Polia',
      category: 'Costas',
      targetedMuscles: ['Latíssimo do dorso', 'Dorsais'],
      description: 'Focado no latíssimo do dorso e nos músculos dorsais, este exercício é realizado na polia.',
      equipmentNeeded: ['Máquina de Polia'],
      days: ['terça-feira', 'sexta-feira'],
    ),
    Exercise(
      id: '13',
      name: 'Remada Sentada na Polia',
      category: 'Costas',
      targetedMuscles: ['Dorsais', 'Latíssimo do dorso'],
      description: 'Exercício que trabalha os dorsais e o latíssimo do dorso, realizado numa máquina de polia na posição sentada.',
      equipmentNeeded: ['Máquina de Polia'],
      days: ['terça-feira', 'sexta-feira'],
    ),
    Exercise(
      id: '14',
      name: 'Voador Inverso no Peck Deck',
      category: 'Costas',
      targetedMuscles: ['Deltoides posteriores'],
      description: 'Este exercício foca nos deltoides posteriores, sendo realizado na máquina Peck Deck configurada para movimentos inversos.',
      equipmentNeeded: ['Máquina Peck Deck'],
      days: ['terça-feira', 'sexta-feira'],
    ),
    Exercise(
      id: '15',
      name: 'Elevação Lateral com Halteres',
      category: 'Ombros',
      targetedMuscles: ['Deltoides médios'],
      description: 'Focado nos deltoides médios, este exercício é realizado em pé, elevando halteres lateralmente.',
      equipmentNeeded: ['Halteres'],
      days: ['segunda-feira', 'quinta-feira'],
    ),
    Exercise(
      id: '16',
      name: 'Elevação Lateral na Polia',
      category: 'Ombros',
      targetedMuscles: ['Deltoides médios'],
      description: 'Exercício para isolamento dos deltoides médios, realizado com polia.',
      equipmentNeeded: ['Polia'],
      days: ['segunda-feira', 'quinta-feira'],
    ),
    Exercise(
      id: '17',
      name: 'Agachamento',
      category: 'Pernas',
      targetedMuscles: ['Quadríceps', 'Glúteos', 'Isquiotibiais'],
      description: 'Exercício fundamental para o desenvolvimento das pernas, envolvendo quadríceps, glúteos e isquiotibiais.',
      equipmentNeeded: ['Barra', 'Pesos'],
      days: ['sábado'],
    ),
    Exercise(
      id: '18',
      name: 'Leg Press',
      category: 'Pernas',
      targetedMuscles: ['Quadríceps', 'Glúteos', 'Isquiotibiais'],
      description: 'Focado em fortalecer as pernas, especialmente quadríceps, glúteos e isquiotibiais, realizado na máquina de Leg Press.',
      equipmentNeeded: ['Máquina de Leg Press'],
      days: ['sábado'],
    ),
    Exercise(
      id: '19',
      name: 'Extensão de Pernas',
      category: 'Pernas',
      targetedMuscles: ['Quadríceps'],
      description: 'Exercício que isola os quadríceps, realizado em máquina específica para extensão de pernas.',
      equipmentNeeded: ['Máquina de Extensão de Pernas'],
      days: ['sábado'],
    ),
    Exercise(
      id: '20',
      name: 'Flexão de Pernas',
      category: 'Pernas',
      targetedMuscles: ['Isquiotibiais'],
      description: 'Este exercício foca nos isquiotibiais, realizado em máquina específica para flexão de pernas.',
      equipmentNeeded: ['Máquina de Flexão de Pernas'],
      days: ['sábado'],
    ),
    Exercise(
      id: '21',
      name: 'Curls de Bíceps com Barra',
      category: 'Braços',
      targetedMuscles: ['Bíceps'],
      description: 'Exercício clássico para fortalecimento dos bíceps, realizado com uma barra.',
      equipmentNeeded: ['Barra'],
      days: ['terça-feira', 'sexta-feira'],
    ),
    Exercise(
      id: '22',
      name: 'Tríceps na Polia Alta',
      category: 'Braços',
      targetedMuscles: ['Tríceps'],
      description: 'Exercício para trabalhar os tríceps, realizado na polia alta com corda ou barra.',
      equipmentNeeded: ['Polia Alta', 'Corda ou Barra'],
      days: ['segunda-feira', 'quinta-feira'],
    ),
    Exercise(
      id: '23',
      name: 'Desenvolvimento de Ombros com Halteres',
      category: 'Ombros',
      targetedMuscles: ['Deltoides'],
      description: 'Exercício para desenvolvimento completo dos ombros, realizado com halteres.',
      equipmentNeeded: ['Halteres'],
      days: ['segunda-feira', 'quinta-feira'],
    ),
    Exercise(
      id: '24',
      name: 'Remada Curvada com Barra',
      category: 'Costas',
      targetedMuscles: ['Dorsais', 'Latíssimo do dorso'],
      description: 'Fortalecimento das costas, focando nos músculos dorsais e no latíssimo do dorso, realizado com barra.',
      equipmentNeeded: ['Barra'],
      days: ['terça-feira', 'sexta-feira'],
    ),
    Exercise(
      id: '25',
      name: 'Puxada no Pulley Alto para Trás',
      category: 'Costas',
      targetedMuscles: ['Latíssimo do dorso'],
      description: 'Exercício no pulley alto para trabalhar a parte posterior dos ombros e o latíssimo do dorso.',
      equipmentNeeded: ['Máquina de Pulley Alto'],
      days: ['terça-feira', 'sexta-feira'],
    ),Exercise(
      id: '26',
      name: 'Elevação de Panturrilha em Pé',
      category: 'Pernas',
      targetedMuscles: ['Panturrilhas'],
      description: 'Exercício destinado ao fortalecimento das panturrilhas, realizado em pé.',
      equipmentNeeded: ['Máquina de Elevação de Panturrilha'],
      days: ['sábado'],
    ),
    Exercise(
      id: '27',
      name: 'Elevação de Panturrilha Sentado',
      category: 'Pernas',
      targetedMuscles: ['Panturrilhas'],
      description: 'Focado nas panturrilhas, este exercício é realizado sentado, ideal para variação de estímulo.',
      equipmentNeeded: ['Máquina de Elevação de Panturrilha Sentado'],
      days: ['sábado'],
    ),
    Exercise(
      id: '28',
      name: 'Abdução de Pernas',
      category: 'Pernas',
      targetedMuscles: ['Glúteos', 'Abdutores'],
      description: 'Exercício que trabalha os glúteos e abdutores, realizado em máquina específica para abdução.',
      equipmentNeeded: ['Máquina de Abdução de Pernas'],
      days: ['sábado'],
    ),
    Exercise(
      id: '29',
      name: 'Adução de Pernas',
      category: 'Pernas',
      targetedMuscles: ['Adutores'],
      description: 'Visa o fortalecimento dos músculos adutores, realizado em máquina específica para adução.',
      equipmentNeeded: ['Máquina de Adução de Pernas'],
      days: ['sábado'],
    ),
    Exercise(
      id: '30',
      name: 'Agachamento Frontal',
      category: 'Pernas',
      targetedMuscles: ['Quadríceps', 'Glúteos', 'Isquiotibiais'],
      description: 'Variação do agachamento que coloca mais ênfase nos quadríceps, realizado com a barra à frente do corpo.',
      equipmentNeeded: ['Barra'],
      days: ['sábado'],
    ),
  ];

  static List<Exercise> getExercisesForUser(SelectionData userPreferences) {
    // Implement more complex logic based on userPreferences if necessary
    return _exercises.where((exercise) => userPreferences.mainGoal == exercise.category).toList();
  }
}